site_name: Assembly finder
repo_url: https://github.com/metagenlab/assembly_finder
site_author: Farid Chaabane
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Inputs: inputs.md
  - Outputs: outputs.md
  - Examples: examples.md 
