

args: 
    input:
    output:
    taxonkit:
    limit:
    requests:
    compressed:
    include:
    source:
    taxon:
    reference:
    assembly_level:
    annotated:
    atypical:
    mag:
    rank:
    nrank:
    
links:
    taxdump: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
