args:
  annotated:
  api_key:
  assembly_level:
  atypical:
  compressed:
  conda_prefix:
  configfile:
  include:
  input:
  level:
  limit:
  log:
  mag:
  nrank:
  output:
  print_versions:
  profile:
  rank:
  snake_args: []
  snake_default:
    - --printshellcmds
    - --nolock
    - --show-failed-logs
  source:
  summary:
  system_config:
  taxon:
  taxonkit:
  threads:
  use_conda:
headers:
  lineage: tax_id,rank,name,kingdom,phylum,class,order,family,genus,species
links:
  taxdump: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
