args:
  annotated:
  api_key:
  assembly_level:
  atypical:
  compressed:
  conda_prefix:
  configfile:
  include:
  input:
  limit:
  log:
  mag:
  nrank:
  output:
  print_versions:
  profile:
  rank:
  reference:
  snake_args:
  snake_default:
  source:
  system_config:
  taxon:
  taxonkit:
  threads:
  use_conda:

links:
  taxdump: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
headers:
  lineage: "tax_id,rank,name,kingdom,phylum,class,order,family,genus,species"
