###########assembly finder config
outdir: outdir_name
input: path/to/input_table or comma seperated string of inputs
NCBI_key: your_ncbi_api_key
NCBI_email: your_ncbi_email
##Parameters for search_assemblies function
uid: False #If inputs are UIDs or not
db: refseq #Download from either refseq or genbank
assembly_level: complete_genome #Download complete genome, chromosome, contig or scaffold
refseq_category: all #Download reference,representative or all
annotation: True #Only select assemblies with annotation
exclude: 'metagenome' #Assemblies to exclude from search
Rank_to_filter_by: species #Filter by species
n_by_rank: 1 #Get 1 assembly per rank
n_by_entry: all #By default select all found assemblies per input
donwloader: aspera #Use either aspera or wget to download assemblies


