include: "bin/find_assemblies.smk"


rule all_download:
    input:
        os.path.join(outdir, "assembly_summary.tsv"),
        os.path.join(outdir, "sequence_report.tsv"),
        os.path.join(outdir, "sequence_taxonomy.tsv"),
