include: "bin/find_assemblies.smk"


rule all_download:
    input:
        downloads,
        os.path.join(outdir, "assembly_summary.tsv"),
        os.path.join(outdir, "sequence_summary.tsv"),
        os.path.join(outdir, "taxonomy_summary.tsv"),
        os.path.join(outdir, "clean.txt"),
