name: Rich-codex
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tool
        run: pip install .

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg
          terminal_width: 80
          skip_git_checks: "true"
